### ISSUE TITLE
Getting `InvalidRequestError` when running the backend with `uvicorn`

### ISSUE THREAD

**Issue by wiseaidev** [ethyca/fides#1234]
### Bug Description

Hey everyone. I am trying to run the backend alone with `uvicorn`, and it seems like there is a duplicate table name or a duplicated module load or things of that nature.

#### Steps to Reproduce

1. Create a virtualenv: `python -m venv .venv`.
2. Activate the virtualenv: `source .venv/bin/activate`.
3. Install all required dependencies: `pip install -r requirements.txt`.
4. cd into the `src` folder: `cd src`
5. run the backend with `uvicorn`: `uvicorn fides.api.main:start_webserver --reload`

### Expected behavior

The backend should run as expected.

### Screenshots

I will provide a full stack trace instead of screenshots:

<details>
<summary><code>stack trace</code></summary>

```sh

INFO:     Will watch for changes in these directories: ['/home/harmouch/Desktop/open-source/fides/src']
INFO:     Uvicorn running on http://127.0.0.1:8000 (Press CTRL+C to quit)
INFO:     Started reloader process [9053] using watchgod
Startup configuration: reloading = False, dev_mode = False
Startup configuration: pii logging = False
Process SpawnProcess-1:
Traceback (most recent call last):
  File "/home/harmouch/.pyenv/versions/3.9.10/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/harmouch/.pyenv/versions/3.9.10/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/harmouch/Desktop/open-source/fides/.venv/lib/python3.9/site-packages/uvicorn/subprocess.py", line 76, in subprocess_started
    target(sockets=sockets)
  File "/home/harmouch/Desktop/open-source/fides/.venv/lib/python3.9/site-packages/uvicorn/server.py", line 60, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "/home/harmouch/.pyenv/versions/3.9.10/lib/python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "uvloop/loop.pyx", line 1517, in uvloop.loop.Loop.run_until_complete
  File "/home/harmouch/Desktop/open-source/fides/.venv/lib/python3.9/site-packages/uvicorn/server.py", line 67, in serve
    config.load()
  File "/home/harmouch/Desktop/open-source/fides/.venv/lib/python3.9/site-packages/uvicorn/config.py", line 458, in load
    self.loaded_app = import_from_string(self.app)
  File "/home/harmouch/Desktop/open-source/fides/.venv/lib/python3.9/site-packages/uvicorn/importer.py", line 21, in import_from_string
    module = importlib.import_module(module_str)
  File "/home/harmouch/.pyenv/versions/3.9.10/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/harmouch/Desktop/open-source/fides/src/./fides/api/main.py", line 50, in <module>
    from fides.api.ops.api.v1.api import api_router
  File "/home/harmouch/Desktop/open-source/fides/src/./fides/api/ops/api/v1/api.py", line 1, in <module>
    from fides.api.ops.api.v1.endpoints import (
  File "/home/harmouch/Desktop/open-source/fides/src/./fides/api/ops/api/v1/endpoints/connection_endpoints.py", line 43, in <module>
    from fides.api.ops.schemas.connection_configuration import (
  File "/home/harmouch/Desktop/open-source/fides/src/./fides/api/ops/schemas/connection_configuration/__init__.py", line 3, in <module>
    from fidesops.ops.models.connectionconfig import ConnectionType
  File "/home/harmouch/Desktop/open-source/fides/.venv/lib/python3.9/site-packages/fidesops/ops/models/connectionconfig.py", line 96, in <module>
    class ConnectionConfig(Base):
  File "/home/harmouch/Desktop/open-source/fides/.venv/lib/python3.9/site-packages/sqlalchemy/orm/decl_api.py", line 75, in __init__
    _as_declarative(reg, cls, dict_)
  File "/home/harmouch/Desktop/open-source/fides/.venv/lib/python3.9/site-packages/sqlalchemy/orm/decl_base.py", line 126, in _as_declarative
    return _MapperConfig.setup_mapping(registry, cls, dict_, None, {})
  File "/home/harmouch/Desktop/open-source/fides/.venv/lib/python3.9/site-packages/sqlalchemy/orm/decl_base.py", line 177, in setup_mapping
    return cfg_cls(registry, cls_, dict_, table, mapper_kw)
  File "/home/harmouch/Desktop/open-source/fides/.venv/lib/python3.9/site-packages/sqlalchemy/orm/decl_base.py", line 310, in __init__
    self._setup_table(table)
  File "/home/harmouch/Desktop/open-source/fides/.venv/lib/python3.9/site-packages/sqlalchemy/orm/decl_base.py", line 799, in _setup_table
    table_cls(
  File "<string>", line 2, in __new__
  File "/home/harmouch/Desktop/open-source/fides/.venv/lib/python3.9/site-packages/sqlalchemy/util/deprecations.py", line 298, in warned
    return fn(*args, **kwargs)
  File "/home/harmouch/Desktop/open-source/fides/.venv/lib/python3.9/site-packages/sqlalchemy/sql/schema.py", line 577, in __new__
    raise exc.InvalidRequestError(
sqlalchemy.exc.InvalidRequestError: Table 'connectionconfig' is already defined for this MetaData instance.  Specify 'extend_existing=True' to redefine options and columns on an existing Table object.

```
</details>

### Environment

* Version: `1.8.5+632.gddc80928.dirty` (unified-2 branch)
* OS: ubuntu 20.04
* Python Version: 3.9.10
* Docker Version: Not required.

### Additional context

That's pretty much it.

### Question

Is there an easy way to run the backend only?

**Comment by sanders41** [comment]
Thanks for the report. I haven't seen this error before, but I will look into it.

As for an easy way to run the backend only, not on its own. Things are fairly tightly tied to running in docker. `nox -s dev -- shell` will start the container with a terminal in the container to interact with.
