### ISSUE TITLE
Application error when loading privacy center.

### ISSUE THREAD

**Issue by sanders41** [ethyca/fides#1279]
### Bug Description

When I log into the privacy center I am getting and error when the page tries to load `Application error: a client-side exception has occurred (see the browser console for more information).`

```console
GET http://localhost:8080/api/v1/plus/health 404 (Not Found)

TypeError: Cannot read properties of undefined (reading 'bg')
    at n.Z (index-44f06aeae903c754.js:1:2862)
    at oo (framework-bb5c596eafb42b22.js:1:59416)
    at Ku (framework-bb5c596eafb42b22.js:1:111716)
    at Li (framework-bb5c596eafb42b22.js:1:98957)
    at Ni (framework-bb5c596eafb42b22.js:1:98885)
    at Pi (framework-bb5c596eafb42b22.js:1:98748)
    at bi (framework-bb5c596eafb42b22.js:1:95714)
    at framework-bb5c596eafb42b22.js:1:45208
    at t.unstable_runWithPriority (framework-bb5c596eafb42b22.js:1:129354)
    at Ql (framework-bb5c596eafb42b22.js:1:44985)
```

#### Steps to Reproduce

1. `nox -s dev`
1. Navigate to `http://localhost:8080`
1. Log in with `root_user`

### Expected behavior

Page should load without error.

### Screenshots

<img width="1432" alt="Screen Shot 2022-10-07 at 7 00 32 PM" src="https://user-images.githubusercontent.com/25045024/194673446-3453a956-fe4c-4d3f-a979-dc8d67bf3b15.png">

### Environment

* Version:
* OS:
* Python Version:
* Docker Version:

### Additional context

_Add any other context about the problem here._

**Comment by allisonking** [comment]
I just tried to reproduce this but was able to log in fine without a console error (besides the 404 on the health endpoint, which [is expected](https://github.com/ethyca/fides/issues/1052)). A few clarifying questions:

* Do you mean the admin-ui as opposed to the privacy center? (privacy center doesn't come up with just `nox -s dev`, I believe. and doesn't have a sign in page as far as I know)
* Have you built/copied your local UI lately? it's possible this was a bug at one point, and that's when you did your build/copy, and then it got fixed since then (hence why I can't repro?). The docker compose mounts over the UI folder, so if you haven't run an `npm run prod-export` in the `admin-ui` folder recently, it might be worth running that then reloading your server to see if that fixes things.
  * There's this PR where you [fixed this volume mounting problem](https://github.com/ethyca/fidesops/pull/1266). maybe that solution needs to be put back in after unified-fides? Although... ⬇️ 
  * Normally what I would do is run the prod image which will have the built frontend files and run that without the volume mount. However I do this very infrequently, since I'm mostly in the development frontend as opposed to the built one

**Comment by sanders41** [comment]
I did mean admin ui! Update the description thanks. I will check on the other suggestions.

**Comment by sanders41** [comment]
After pulling the latest main the error is resolved so closing.
