### ISSUE TITLE
Privacy center config identity inputs should be optional

### ISSUE THREAD

**Issue by allisonking** [ethyca/fides#2259]
### Bug Description

Reported by @RobertKeyser, when bringing up the privacy center on `main` we get a typescript error:

```
info  - Linting and checking validity of types...
Failed to compile.

./constants/index.ts:6:14
Type error: Type '{ actions: { description: string; icon_path: string; identity_inputs: { email: string; name: string; phone: string; }; policy_key: string; title: string; }[]; consent: { consentOptions: { cookieKeys: string[]; ... 5 more ...; url: string; }[]; cookieName: string; description: string; icon_path: string; title: string...' is not assignable to type 'Config'.
  Types of property 'consent' are incompatible.
    Property 'identity_inputs' is missing in type '{ consentOptions: { cookieKeys: string[]; default: boolean; description: string; fidesDataUseKey: string; highlight: boolean; name: string; url: string; }[]; cookieName: string; description: string; icon_path: string; title: string; }' but required in type '{ icon_path: string; title: string; description: string; identity_inputs: Record<string, string>; consentOptions: ConfigConsentOption[]; }'.

  4 | import configJson from "~/config/config.json";
  5 | 
> 6 | export const config: Config = configJson;
    |              ^
  7 | 
  8 | // Compute the host URL for the server, while being backwards compatible with
  9 | // the previous "fidesops_host_***" configuration

> Build error occurred
Error: Call retries were exceeded
    at ChildProcessWorker.initialize (/app/node_modules/next/dist/compiled/jest-worker/index.js:1:11661)
    at ChildProcessWorker._onExit (/app/node_modules/next/dist/compiled/jest-worker/index.js:1:12599)
    at ChildProcess.emit (node:events:513:28)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:293:12) {
  type: 'WorkerError'
}
```

#### Steps to Reproduce

1. _Do this..._
1. _Then This..._

### Expected behavior

_A description of what you expected to happen._

### Screenshots

_If applicable, add screenshots to help explain your problem._

### Environment

* Version:
* OS:
* Python Version:
* Docker Version:

### Additional context

_Add any other context about the problem here._

**Comment by mfbrown** [comment]
Tagging @ssangervasi here because he's been working on the consent options a lot lately.
