### ISSUE TITLE
mssql connector raises the error with generate-dataset

### ISSUE THREAD

**Issue by iokamoto-sm** [ethyca/fides#334]
### Bug Description

This is probably the issue with pyodbc configuration. I followed the install from docker and installed fidesctl with mssql connector so I can test fidesctl generate-dataset command against SQL Server. It failed with IM002 error.

#### Steps to Reproduce
```
git clone https://github.com/ethyca/fides.git
git switch --detach 1.2.0
cd fides
make build
docker tag ethyca/fidesctl:<tag> ethyca/fidesctl:local
fidesctl generate-dataset mssql+pyodbc://<username>:<password>@<server>:<port>/<database> test.yml

Database connection failed with engine:
Engine(mssql+pyodbc://<username>:***@<server>:<port>)!
(pyodbc.InterfaceError) ('IM002', '[IM002] [unixODBC][Driver Manager]Data source name not found and no default driver specified (0) (SQLDriverConnect)')
```

### Expected behavior

It is expected to produce test.yml from the database.

### Screenshots

_If applicable, add screenshots to help explain your problem._

### Environment

* Version: 1.2.0
* OS: Mac OS X 12.1
* Python Version: 3.8.5
* Docker Version: 20.10.8

### Additional context

_Add any other context about the problem here._

**Comment by iokamoto-sm** [comment]
I could connect to the database by adding driver to connection string like:

`fidesctl generate-dataset mssql+pyodbc://<username>:<password>@<server>:<port>/<database>?driver=ODBC+Driver+17+for+SQL+Server test.yml`

However, generate-dataset raised the following error.

```
Traceback (most recent call last):
  File "/opt/fides/fidesctl/bin/fidesctl", line 8, in <module>
    sys.exit(cli())
  File "/opt/fides/fidesctl/lib/python3.9/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/opt/fides/fidesctl/lib/python3.9/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/opt/fides/fidesctl/lib/python3.9/site-packages/click/core.py", line 1289, in invoke
    rv.append(sub_ctx.command.invoke(sub_ctx))
  File "/opt/fides/fidesctl/lib/python3.9/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/fides/fidesctl/lib/python3.9/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/opt/fides/fidesctl/lib/python3.9/site-packages/click/decorators.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/opt/fides/fidesctl/lib/python3.9/site-packages/fidesctl/cli/cli.py", line 140, in generate_dataset
    _generate_dataset.generate_dataset(connection_string, output_filename)
  File "/opt/fides/fidesctl/lib/python3.9/site-packages/fidesctl/core/generate_dataset.py", line 297, in generate_dataset
    collections = create_dataset_collections(db_collections)
  File "/opt/fides/fidesctl/lib/python3.9/site-packages/fidesctl/core/generate_dataset.py", line 111, in create_dataset_collections
    table_manifests = [
  File "/opt/fides/fidesctl/lib/python3.9/site-packages/fidesctl/core/generate_dataset.py", line 112, in <listcomp>
    Dataset(
  File "pydantic/main.py", line 329, in pydantic.main.BaseModel.__init__
  File "pydantic/main.py", line 1022, in pydantic.main.validate_model
  File "pydantic/fields.py", line 854, in pydantic.fields.ModelField.validate
  File "pydantic/fields.py", line 1071, in pydantic.fields.ModelField._validate_singleton
  File "pydantic/fields.py", line 1118, in pydantic.fields.ModelField._apply_validators
  File "pydantic/class_validators.py", line 313, in pydantic.class_validators._generic_validator_basic.lambda12
  File "/opt/fides/fidesctl/lib/python3.9/site-packages/fideslang/validation.py", line 25, in validate
    raise FidesValidationError(
fideslang.validation.FidesValidationError: FidesKey must only contain alphanumeric characters, '.' or '_'.
```

**Comment by ThomasLaPiana** [comment]
@iokamoto-sm what's going on here appears to be that the database name, which is used to automatically generate the `fides_key`, has illegal characters in it. I would guess that you're using a hyphen in your database names? I think it makes sense for us to broaden the `fides_key` criteria to also include hyphens since I would bet a lot of people prefer those over underscores

**Comment by iokamoto-sm** [comment]
Hi @ThomasLaPiana , the database name is `sm_AccountsNew` and it has only alphabets and `_`. Table names are mostly the same. But one table name contains `.` like `dbo.__sm_analyze`. I sent @iamkelllly the full table list in csv format via slack.

**Comment by ThomasLaPiana** [comment]
@iokamoto-sm how about the hostname?

**Comment by iokamoto-sm** [comment]
@ThomasLaPiana , yes, it does have `-` hyphen like `mt1-db-sm-accountsnew`.

**Comment by ThomasLaPiana** [comment]
@iokamoto-sm understood, it will create a key from the hostname as well. It sounds like the easiest way forward here is to expand the fides_key allowed characters to include a hyphen, that should solve this problem and I think you definitely aren't the only person that will want to use hyphens!
