### ISSUE TITLE
Cannot Migrate Application Locally

### ISSUE THREAD

**Issue by pattisdr** [ethyca/fides#3616]
### Bug Description

There has been some rearranging of the directory structure lately and now you can no longer run or generate migrations locally.  

This method works: https://github.com/ethyca/fides/blob/main/src/fides/api/db/database.py#LL26C2-L26C2 however which is why our tests are passing:
> The migration commands within the application run via Alembic's Python API and the Config has already been loaded at that time so I'm assuming that's why it works there and doesn't work via the CLI?

#### Steps to Reproduce

- nox -s dev -- shell.
- cd src/fides/api
- alembic revision -m "test_migration" --autogenerate

```
Traceback (most recent call last):
  File "/opt/fides/bin/alembic", line 8, in <module>
    sys.exit(main())
  File "/opt/fides/lib/python3.10/site-packages/alembic/config.py", line 590, in main
    CommandLine(prog=prog).main(argv=argv)
  File "/opt/fides/lib/python3.10/site-packages/alembic/config.py", line 584, in main
    self.run_cmd(cfg, options)
  File "/opt/fides/lib/python3.10/site-packages/alembic/config.py", line 561, in run_cmd
    fn(
  File "/opt/fides/lib/python3.10/site-packages/alembic/command.py", line 322, in upgrade
    script.run_env()
  File "/opt/fides/lib/python3.10/site-packages/alembic/script/base.py", line 569, in run_env
    util.load_python_file(self.dir, "env.py")
  File "/opt/fides/lib/python3.10/site-packages/alembic/util/pyfiles.py", line 94, in load_python_file
    module = load_module_py(module_id, path)
  File "/opt/fides/lib/python3.10/site-packages/alembic/util/pyfiles.py", line 110, in load_module_py
    spec.loader.exec_module(module)  # type: ignore
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/fides/src/fides/api/migrations/env.py", line 6, in <module>
    from fides.api.util.logger import setup as setup_fidesapi_logger
  File "/fides/src/fides/api/util/logger.py", line 15, in <module>
    from fides.core.config import CONFIG
  File "/fides/src/fides/core/config/__init__.py", line 28, in <module>
    from .security_settings import SecuritySettings
  File "/fides/src/fides/core/config/security_settings.py", line 10, in <module>
    from fides.api.api.v1.scope_registry import SCOPE_REGISTRY
  File "/fides/src/fides/api/api/v1/__init__.py", line 8, in <module>
    from .endpoints.admin import ADMIN_ROUTER
  File "/fides/src/fides/api/api/v1/endpoints/admin.py", line 8, in <module>
    from fides.api.db.database import configure_db, reset_db
  File "/fides/src/fides/api/db/database.py", line 15, in <module>
    from fides.api.db.base import Base  # type: ignore[attr-defined]
  File "/fides/src/fides/api/db/base.py", line 5, in <module>
    from fides.api.models.application_config import ApplicationConfig
  File "/fides/src/fides/api/models/application_config.py", line 18, in <module>
    from fides.core.config import CONFIG, FidesConfig
ImportError: cannot import name 'CONFIG' from partially initialized module 'fides.core.config' (most likely due to a circular import) (/fides/src/fides/core/config/__init__.py)
```

### Expected behavior

We need to be able to generate migrations and do `alembic upgrade head` and `alembic downgrade -1` locally!

### Screenshots

_If applicable, add screenshots to help explain your problem._

### Environment

* Version:
* OS:
* Python Version:
* Docker Version:

### Additional context

_Add any other context about the problem here._

**Comment by adamsachs** [comment]
(notes as i go) ... 

- circular import seems to be:
`src/fides/core/config/__init__.py` --> `src/fides/core/config/security_settings.py` --> `fides.api.api.v1.scope_registry.SCOPE_REGISTRY` -->  `src/fides/api/api/v1/__init__.py` --> `src.fides.api.api.v1.endpoints.admin.ADMIN_ROUTER` --> `fides.core.config.CONFIG`

**Comment by ThomasLaPiana** [comment]
yep, I dealt with a similar one recently when I rearranged `fides.api` but I had fixed it (only for the build apparently)

The way we reach across modules is a bit problematic, and these are legitimate issues. 

@adamsachs I'm going to dig in and do some reorganization and cleanup here

**Comment by Roger-Ethyca** [comment]
moving to done
