### ISSUE TITLE
SaaS update payload with complex values fails

### ISSUE THREAD

**Issue by galvana** [ethyca/fides#3899]
### Bug Description

The preparation of the `<all_object_fields>` placeholder in the SaaS connector logic throws the following exception under certain cases
```
fides.api.common_exceptions.FidesopsException: 'unflatten_dict' expects a flattened dictionary as input.
```

This happens if an API response returns more details than we had available when we created the original dataset. In the example below, we knew that `metadata` and `substitution_data` were objects but since we didn't specify the specific fields Fides isn't able to generate a fully "flattened" dictionary. This causes `unflatten_dict` to throw an error.
```
{
    "address.email": "2a3aaa22b2ccce15ef7a1e94ee@email.com",
    "address.name": "MASKED",
    "metadata":
    {
        "age": "24",
        "place": "Bedrock"
    },
    "return_path": "",
    "substitution_data":
    {
        "favorite_color": "SparkPost Orange",
        "job": "Software Engineer"
    },
    "tags":
    [
        "greeting",
        "prehistoric",
        "fred",
        "flintstone"
    ]
}
```

#### Steps to Reproduce

1. Run the tests for the Sparkpost connector

### Expected behavior

Fides should be able to unflatten a partially flattened dictionary
```
{
    "address":
    {
        "email": "2a3aaa22b2ccce15ef7a1e94ee@email.com",
        "name": "MASKED"
    },
    "metadata":
    {
        "age": "24",
        "place": "Bedrock"
    },
    "return_path": "",
    "substitution_data":
    {
        "favorite_color": "SparkPost Orange",
        "job": "Software Engineer"
    },
    "tags":
    [
        "greeting",
        "prehistoric",
        "fred",
        "flintstone"
    ]
}
```

**Comment by rsilvery** [comment]
@galvana  is this still an issue? @Kelsey-Ethyca  priority?

**Comment by galvana** [comment]
@rsilvery, this is the top priority for connector framework issues. This wasn't an issue since SaaS connector development was paused for a bit but we just ran into it again with @MarcGEthyca's first connector.

**Comment by RobertKeyser** [comment]
Seen in a customer environment today: 

```
[2023-09-26 12:49:21,796: WARNING/ForkPoolWorker-2] Traceback (most recent call last):
[2023-09-26 12:49:21,796: WARNING/ForkPoolWorker-2]   File "/usr/local/lib/python3.10/site-packages/fides/api/task/graph_task.py", line 98, in result
return func(*args, **kwargs)
[2023-09-26 12:49:21,796: WARNING/ForkPoolWorker-2]   File "/usr/local/lib/python3.10/site-packages/fides/api/task/graph_task.py", line 598, in erasure_request
output = self.connector.mask_data(
[2023-09-26 12:49:21,796: WARNING/ForkPoolWorker-2]   File "/usr/local/lib/python3.10/site-packages/fides/api/service/connectors/saas_connector.py", line 414, in mask_data
prepared_request = query_config.generate_update_stmt(
[2023-09-26 12:49:21,796: WARNING/ForkPoolWorker-2]   File "/usr/local/lib/python3.10/site-packages/fides/api/service/connectors/saas_query_config.py", line 319, in generate_update_stmt
param_values: Dict[str, Any] = self.generate_update_param_values(
[2023-09-26 12:49:21,796: WARNING/ForkPoolWorker-2]   File "/usr/local/lib/python3.10/site-packages/fides/api/service/connectors/saas_query_config.py", line 408, in generate_update_param_values
complete_object: Dict[str, Any] = unflatten_dict(
[2023-09-26 12:49:21,796: WARNING/ForkPoolWorker-2]   File "/usr/local/lib/python3.10/site-packages/fides/api/util/saas_util.py", line 220, in unflatten_dict
raise FidesopsException(
[2023-09-26 12:49:21,796: WARNING/ForkPoolWorker-2] fides.api.common_exceptions.FidesopsException: 'unflatten_dict' expects a flattened dictionary as input.
2023-09-26 12:49:22.797 | WARNING  | fides.api.task.graph_task:log_end:431 - Ending pri_47bf4bc8-ae9f-4c7f-ae6d-e540faee0e7e, kustomer_api:customer with failure MASKED
```
