### ISSUE TITLE
fidesctl generate dataset command fails with 1.4.x

### ISSUE THREAD

**Issue by iokamoto-sm** [ethyca/fides#447]
### Bug Description

`fidesctl generate dataset` command fails with the error, `TypeError: generate_dataset() got an unexpected keyword argument 'filename'`.

You may already have fixed this issue in release-1.4.2 branch after refactoring. But 1.4.2 tag still has this issue.

#### Steps to Reproduce

1. git clone https://github.com/ethyca/fides.git
2. git switch --detach 1.4.2
3. make build
4. perform `fidesctl generate dataset`
5. the error, `TypeError: generate_dataset() got an unexpected keyword argument 'filename`, is raised.

### Expected behavior

fidesctl generate dataset should not fail.

### Screenshots

n.a

### Environment

* Version: 1.4.0 / 1.4.2
* OS: macOS monterey 12.3.1 / Ubuntu 20.04.4 LTS (Focal Fossa)
* Python Version: 3.9.12
* Docker Version: 20.10.12, build e91ed57

### Additional context
This is the terminal log with traceback.
```
root@b1c4fe4c3ab3:/opt/fides/fidesctl/src/fidesctl/cli# fidesctl generate dataset mssql+pyodbc://<username>:<password>@<server>:<port>/<db_name>?driver=ODBC+Driver+17+for+SQL+Server test123.yaml
Traceback (most recent call last):
  File "/opt/fides/fidesctl/bin/fidesctl", line 33, in <module>
    sys.exit(load_entry_point('fidesctl', 'console_scripts', 'fidesctl')())
  File "/opt/fides/fidesctl/lib/python3.9/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/opt/fides/fidesctl/lib/python3.9/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/opt/fides/fidesctl/lib/python3.9/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/opt/fides/fidesctl/lib/python3.9/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/opt/fides/fidesctl/lib/python3.9/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/fides/fidesctl/lib/python3.9/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/opt/fides/fidesctl/lib/python3.9/site-packages/click/decorators.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/opt/fides/fidesctl/src/fidesctl/cli/generate_commands.py", line 35, in generate_dataset
    with_analytics(
  File "/opt/fides/fidesctl/src/fidesctl/cli/utils.py", line 98, in with_analytics
    raise err
  File "/opt/fides/fidesctl/src/fidesctl/cli/utils.py", line 94, in with_analytics
    return command_handler(**kwargs)
TypeError: generate_dataset() got an unexpected keyword argument 'filename'
```

**Comment by earmenda** [comment]
@iokamoto-sm this was fixed in https://github.com/ethyca/fides/pull/422

We plan on releasing 1.5.0 sometime this week if that works for you

**Comment by iokamoto-sm** [comment]
If 1.5.0 is released this week, that works for me.

**Comment by earmenda** [comment]
1.5.0 has been releases :)
