### ISSUE TITLE
fidesctl export datamap throws `FileNotFoundError`

### ISSUE THREAD

**Issue by NevilleS** [ethyca/fides#452]
### Bug Description

When trying to use `fidesctl export datamap`, I hit an unexpected error due to a missing template. Seems like we aren't packaging that into the `pip` package so it fails locally:
```
(venv) ~/git/fidesdemo% fidesctl export datamap                                                      
Loading resource manifests from: .fides/
Taxonomy successfully created.
Legal Basis undefined for specified Data Use, setting as N/A.
Recipients undefined for specified Data Use, setting as N/A
Legal Basis undefined for specified Data Use, setting as N/A.
Recipients undefined for specified Data Use, setting as N/A
Legal Basis undefined for specified Data Use, setting as N/A.
Recipients undefined for specified Data Use, setting as N/A
Traceback (most recent call last):
  File "/Users/neville/git/fidesdemo/venv/bin/fidesctl", line 8, in <module>
    sys.exit(cli())
  File "/Users/neville/git/fidesdemo/venv/lib/python3.9/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/Users/neville/git/fidesdemo/venv/lib/python3.9/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/Users/neville/git/fidesdemo/venv/lib/python3.9/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/neville/git/fidesdemo/venv/lib/python3.9/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/neville/git/fidesdemo/venv/lib/python3.9/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/neville/git/fidesdemo/venv/lib/python3.9/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/Users/neville/git/fidesdemo/venv/lib/python3.9/site-packages/click/decorators.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/Users/neville/git/fidesdemo/venv/lib/python3.9/site-packages/fidesctl/cli/export_commands.py", line 115, in export_datamap
    with_analytics(
  File "/Users/neville/git/fidesdemo/venv/lib/python3.9/site-packages/fidesctl/cli/utils.py", line 98, in with_analytics
    raise err
  File "/Users/neville/git/fidesdemo/venv/lib/python3.9/site-packages/fidesctl/cli/utils.py", line 94, in with_analytics
    return command_handler(**kwargs)
  File "/Users/neville/git/fidesdemo/venv/lib/python3.9/site-packages/fidesctl/core/export.py", line 389, in export_datamap
    exported_filename = export_datamap_to_excel(
  File "/Users/neville/git/fidesdemo/venv/lib/python3.9/site-packages/fidesctl/core/export_helpers.py", line 82, in export_datamap_to_excel
    shutil.copy(DATAMAP_TEMPLATE, filepath)
  File "/usr/local/Cellar/python@3.9/3.9.10/Frameworks/Python.framework/Versions/3.9/lib/python3.9/shutil.py", line 427, in copy
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "/usr/local/Cellar/python@3.9/3.9.10/Frameworks/Python.framework/Versions/3.9/lib/python3.9/shutil.py", line 264, in copyfile
    with open(src, 'rb') as fsrc:
FileNotFoundError: [Errno 2] No such file or directory: 'src/fidesctl/templates/fides_datamap_template.xlsx'
```

#### Steps to Reproduce

1. `pip install fidesctl`
2. Setup your local config, etc.
3. `fidesctl export datamap`

### Expected behavior

The template should be part of the `pip` package.

### Workaround

I found that if I create a local directory `src/fidesctl/templates/` and download the template from GitHub, I can workaround that. But that's definitely not what we meant :)

### Environment

* Version: 1.4.2
* OS: Mac OSX 12.3.1
* Python Version: 3.9.10
* Docker Version: 20.10.11

**Comment by SteveDMurphy** [comment]
Thanks for bringing this up @NevilleS ! Looking into it today 🙌🏽

**Comment by ThomasLaPiana** [comment]
@SteveDMurphy I'd guess it needs to get added to the `MANIFEST.INI`
