### ISSUE TITLE
Application error on start up - could not translate host name "fidesctl-db" to address: Name or service not known

### ISSUE THREAD

**Issue by waghsac** [ethyca/fides#502]
### Bug Description
I'm new to fides and have set it up using docker desktop. I have pulled an image and created  a container out of it. The container shuts down in a minute automatically. Below is a log snippet pointing at application error on start up.

#### Steps to Reproduce

Download docker desktop for windows and ubuntu
Pull the docker image using: docker pull ethyca/fidesctl:1.5.2-5-gb5f8298
Create a container out of the docker image and start it.
The container only runs for a minute and the cli closes automatically after that.
The logs show the attached error.
[error.txt](https://github.com/ethyca/fides/files/8506269/error.txt)

**Comment by ThomasLaPiana** [comment]
@waghsac can you give us more information around docker version, os, and what command you ran? Everything that's in the bug template helps us figure out what might be causing the issue

Additionally, can you paste the error logs here in plain text? Downloading files can be a security concern for some people

**Comment by waghsac** [comment]
Pasting the log in plain text
2022-04-18 12:49:47.656 | DEBUG    | fidesapi.main:configure_routes:29 - Adding router to fidesctl: DataCategory
2022-04-18 12:49:47.671 | DEBUG    | fidesapi.main:configure_routes:29 - Adding router to fidesctl: DataQualifier
2022-04-18 12:49:47.688 | DEBUG    | fidesapi.main:configure_routes:29 - Adding router to fidesctl: DataSubject
2022-04-18 12:49:47.708 | DEBUG    | fidesapi.main:configure_routes:29 - Adding router to fidesctl: DataUse
2022-04-18 12:49:47.734 | DEBUG    | fidesapi.main:configure_routes:29 - Adding router to fidesctl: Dataset
2022-04-18 12:49:47.806 | DEBUG    | fidesapi.main:configure_routes:29 - Adding router to fidesctl: Organization
2022-04-18 12:49:47.837 | DEBUG    | fidesapi.main:configure_routes:29 - Adding router to fidesctl: Policy
2022-04-18 12:49:47.866 | DEBUG    | fidesapi.main:configure_routes:29 - Adding router to fidesctl: Registry
2022-04-18 12:49:47.877 | DEBUG    | fidesapi.main:configure_routes:29 - Adding router to fidesctl: System
2022-04-18 12:49:48.041 | DEBUG    | fidesapi.main:configure_routes:29 - Adding router to fidesctl: Evaluation
2022-04-18 12:49:48.078 | DEBUG    | fidesapi.main:configure_routes:29 - Adding router to fidesctl: Visualize DataCategory
2022-04-18 12:49:48.080 | DEBUG    | fidesapi.main:configure_routes:29 - Adding router to fidesctl: Visualize DataQualifier
2022-04-18 12:49:48.080 | DEBUG    | fidesapi.main:configure_routes:29 - Adding router to fidesctl: Visualize DataUse
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 3112, in _wrap_pool_connect
    return fn()
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 301, in connect
    return _ConnectionFairy._checkout(self)
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 748, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 419, in checkout
    rec = pool._do_get()
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/pool/impl.py", line 145, in _do_get
    self._dec_overflow()
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/util/compat.py", line 198, in raise_
    raise exception
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/pool/impl.py", line 142, in _do_get
    return self._create_connection()
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 247, in _create_connection
    return _ConnectionRecord(self)
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 362, in __init__
    self.__connect(first_connect_check=True)
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 598, in __connect
    pool.logger.debug("Error on connect(): %s", e)
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/util/compat.py", line 198, in raise_
    raise exception
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 592, in __connect
    connection = pool._invoke_creator(self)
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/create.py", line 576, in connect
    return dialect.connect(*cargs, **cparams)
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 548, in connect
    return self.dbapi.connect(*cargs, **cparams)
  File "/usr/local/lib/python3.8/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: could not translate host name "fidesctl-db" to address: Name or service not known


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/starlette/routing.py", line 540, in lifespan
    async for item in self.lifespan_context(app):
  File "/usr/local/lib/python3.8/site-packages/starlette/routing.py", line 481, in default_lifespan
    await self.startup()
  File "/usr/local/lib/python3.8/site-packages/starlette/routing.py", line 516, in startup
    await handler()
  File "/fides/fidesctl/src/fidesapi/main.py", line 53, in setup_server
    await configure_db(CONFIG.api.sync_database_url)
  File "/fides/fidesctl/src/fidesapi/main.py", line 41, in configure_db
    database.create_db_if_not_exists(database_url)
  File "/fides/fidesctl/src/fidesapi/database/database.py", line 54, in create_db_if_not_exists
    create_database(database_url)
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy_utils/functions/database.py", line 578, in create_database
    with engine.connect() as connection:
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 3066, in connect
    return self._connection_cls(self, close_with_result=close_with_result)
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 91, in __init__
    else engine.raw_connection()
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 3145, in raw_connection
    return self._wrap_pool_connect(self.pool.connect, _connection)
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 3115, in _wrap_pool_connect
    Connection._handle_dbapi_exception_noconnection(
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 2003, in _handle_dbapi_exception_noconnection
    util.raise_(
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/util/compat.py", line 198, in raise_
    raise exception
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 3112, in _wrap_pool_connect
    return fn()
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 301, in connect
    return _ConnectionFairy._checkout(self)
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 748, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 419, in checkout
    rec = pool._do_get()
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/pool/impl.py", line 145, in _do_get
    self._dec_overflow()
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/util/compat.py", line 198, in raise_
    raise exception
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/pool/impl.py", line 142, in _do_get
    return self._create_connection()
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 247, in _create_connection
    return _ConnectionRecord(self)
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 362, in __init__
    self.__connect(first_connect_check=True)
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 598, in __connect
    pool.logger.debug("Error on connect(): %s", e)
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/util/compat.py", line 198, in raise_
    raise exception
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 592, in __connect
    connection = pool._invoke_creator(self)
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/create.py", line 576, in connect
    return dialect.connect(*cargs, **cparams)
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 548, in connect
    return self.dbapi.connect(*cargs, **cparams)
  File "/usr/local/lib/python3.8/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
sqlalchemy.exc.OperationalError: (psycopg2.OperationalError) could not translate host name "fidesctl-db" to address: Name or service not known

(Background on this error at: http://sqlalche.me/e/14/e3q8)

Application startup failed. Exiting.

**Comment by waghsac** [comment]
Docker version 20.10.14, build a224086 (Docker desktop)
OS: Windows 2010 Home

**Comment by sanders41** [comment]
It looks like you don't have Postgres running, is that correct? See if this guide helps https://ethyca.github.io/fides/quickstart/docker/

**Comment by waghsac** [comment]
This is resolved now, thanks.

**Comment by ThomasLaPiana** [comment]
thank you @waghsac ! closing this issue
