### ISSUE TITLE
datamap excel not being generated for custom folder

### ISSUE THREAD

**Issue by waghsac** [ethyca/fides#651]
I have created a different folder and annotated a customer table from open dataset. Although the policy works as expected the datamap creation fails with the below error.

root@615c8dc77c6c:/fides# fidesctl export datamap adw_resources/
Server is reachable and the client/server application versions match.
Loading resource manifests from: adw_resources/
Taxonomy successfully created.
Traceback (most recent call last):
  File "/usr/local/bin/fidesctl", line 33, in <module>
    sys.exit(load_entry_point('fidesctl', 'console_scripts', 'fidesctl')())
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/click/decorators.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/fides/src/fidesctl/cli/commands/export.py", line 115, in export_datamap
    with_analytics(
  File "/fides/src/fidesctl/cli/utils.py", line 124, in with_analytics
    raise err
  File "/fides/src/fidesctl/cli/utils.py", line 120, in with_analytics
    return command_handler(**kwargs)
  File "/fides/src/fidesctl/core/export.py", line 416, in export_datamap
    joined_system_dataset_df = build_joined_dataframe(
  File "/fides/src/fidesctl/core/export.py", line 381, in build_joined_dataframe
    server_resource_dict["organization"][0].security_policy or ""
IndexError: list index out of range

**Comment by NevilleS** [comment]
Hi @waghsac thanks for the report. This is definitely a bug which we'll address quickly; it looks like we're not handling the case where an `Organization` hasn't been defined & applied to the server.

To capture all your organization's relevant metadata, you can author another YAML file for an `Organization` resource, then use `fidesctl apply` to commit that to the system. See the guide here: https://ethyca.github.io/fides/1.6.0/guides/generating_datamap/#organization

If you do that, you'll get a bit further, but I think you'll still be blocked by a known issue we've fixed here: #539

**Comment by SteveDMurphy** [comment]
Thanks for the bug issue @waghsac !!

I _think_ this is a symptom of currently limiting the exported resources to the manifest directory itself (which needs to be changed).
This would then result in collecting the `default_organization` at a minimum if we were pulling all resources stored on the server.

It looks like you are working off of `main` and using Docker, so I'm looking to see if there is a path that can get that resolved quickly to keep you moving and allow some extra time to resolve this fully before our next release. 

In the meantime, you should be able to follow the advice above from @NevilleS to author another YAML for an `Organization` in the `adw_resources/` directory to have the data map export succeed.

Thanks again and more soon!
