### ISSUE TITLE
`fidesctl generate dataset ...` key validation error

### ISSUE THREAD

**Issue by seanpreston** [ethyca/fides#749]
### Bug Description

`fidectl generate dataset db` tries to set the `fides_key` automatically as the name of the dataset, however this fails when the dataset names contain invalid characters like `\`.

#### Steps to Reproduce

1. run `fidesctl generate dataset` on a collection where a table contains a `\` char in its name

### Expected behavior

The command should successfully generate a dataset in either of the following:
- invalid chars are removed / substituted with other chars e.g. `corp\sql_tlshdagent` becomes `corp_sql_tlshdagent`
- users are manually required to enter `fides_key` for each dataset

### Stack trace

```
root@... :/opt/fides/fidesctl# fidesctl generate dataset db mssql+pyodbc://<username>:<password>@{db_hostname}/{table_name}?driver=ODBC+Driver+17+for+SQL+Server {dataset_filename}.yml
Mismatched versions!
Server Version: 1.6.0
CLI Version: 1.6.0+0.gdb7cf8e.dirty
Traceback (most recent call last):
  File "/opt/fides/fidesctl/bin/fidesctl", line 33, in <module>
    sys.exit(load_entry_point('fidesctl', 'console_scripts', 'fidesctl')())
  File "/opt/fides/fidesctl/lib/python3.9/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/opt/fides/fidesctl/lib/python3.9/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/opt/fides/fidesctl/lib/python3.9/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/opt/fides/fidesctl/lib/python3.9/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/opt/fides/fidesctl/lib/python3.9/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/opt/fides/fidesctl/lib/python3.9/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/fides/fidesctl/lib/python3.9/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/opt/fides/fidesctl/lib/python3.9/site-packages/click/decorators.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/opt/fides/fidesctl/src/fidesctl/cli/utils.py", line 168, in wrapper_func
    raise err
  File "/opt/fides/fidesctl/src/fidesctl/cli/utils.py", line 164, in wrapper_func
    return ctx.invoke(func, ctx, *args, **kwargs)
  File "/opt/fides/fidesctl/lib/python3.9/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/opt/fides/fidesctl/src/fidesctl/cli/commands/generate.py", line 43, in generate_dataset_db
    _dataset.generate_dataset_db(
  File "/opt/fides/fidesctl/src/fidesctl/core/dataset.py", line 415, in generate_dataset_db
    db_datasets = create_db_datasets(db_schemas=db_schemas)
  File "/opt/fides/fidesctl/src/fidesctl/core/dataset.py", line 76, in create_db_datasets
    datasets = [
  File "/opt/fides/fidesctl/src/fidesctl/core/dataset.py", line 77, in <listcomp>
    create_db_dataset(schema_name=schema_name, db_tables=db_tables)
  File "/opt/fides/fidesctl/src/fidesctl/core/dataset.py", line 90, in create_db_dataset
    dataset = Dataset(
  File "pydantic/main.py", line 339, in pydantic.main.BaseModel.__init__
  File "pydantic/main.py", line 1038, in pydantic.main.validate_model
  File "pydantic/fields.py", line 857, in pydantic.fields.ModelField.validate
  File "pydantic/fields.py", line 1074, in pydantic.fields.ModelField._validate_singleton
  File "pydantic/fields.py", line 1121, in pydantic.fields.ModelField._apply_validators
  File "pydantic/class_validators.py", line 313, in pydantic.class_validators._generic_validator_basic.lambda12
  File "/opt/fides/fidesctl/src/fideslang/validation.py", line 29, in validate
    raise FidesValidationError(
fideslang.validation.FidesValidationError: FidesKey must only contain alphanumeric characters, '.', '_' or '-'.
```

Aha! Link: https://ethyca.aha.io/features/CTL-99

**Comment by NevilleS** [comment]
My $0.02 is that this `generate` command is creating a `fides_key` automatically based on the database, but I don't think we want to change the rules for `fides_key` too much. Those are intentionally very strict strings because the `fides_key` is meant to be a universal key you can use with the CLI without incident, and special characters like `!` or `$` can cause surprising results in shell prompts!

So I think there's two ways to solve this issue and we should _probably_ do both:
1. Ensure that the auto-generated `fides_key` is guaranteed to be valid, by doing things like stripping invalid characters, etc.
2. Letting the user specify their own `fides_key` instead of using the auto-generated one, e.g. `fidesctl generate dataset db $DB_URL --fides_key my_postgres_dataset`

Personally, I'd want to use option 2 the most, because we also need to remember that `fides_key` needs to be unique to work as expected, whereas databases are often named the same thing. Our current code, for example, creates an autogenerated key like `public` which is really too generic to be used
