### ISSUE TITLE
Issue exporting data map after adding a system in the UI

### ISSUE THREAD

**Issue by mfbrown** [ethyca/fides#805]
### Bug Description
After adding a system through the configuration wizard, when trying to export a data map there is an error. 

#### Steps to Reproduce

1. Run fidesctl 
2. Add a new system by working through the config wizard
3. From the CLI, run `fidesctl export datamap`
4. This results in an error:
`Traceback (most recent call last):
  File "/usr/local/bin/fidesctl", line 33, in <module>
    sys.exit(load_entry_point('fidesctl', 'console_scripts', 'fidesctl')())
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/fides/src/fidesctl/cli/utils.py", line 173, in wrapper_func
    raise err
  File "/fides/src/fidesctl/cli/utils.py", line 169, in wrapper_func
    return ctx.invoke(func, ctx, *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/fides/src/fidesctl/cli/commands/export.py", line 127, in export_datamap
    _export.export_datamap(
  File "/fides/src/fidesctl/core/export.py", line 450, in export_datamap
    joined_system_dataset_df = build_joined_dataframe(server_resource_dict)
  File "/fides/src/fidesctl/core/export.py", line 360, in build_joined_dataframe
    system_output_list = generate_system_records(server_resource_dict)
  File "/fides/src/fidesctl/core/export.py", line 175, in generate_system_records
    data_use = formatted_data_uses[declaration.data_use]
KeyError: 'string'`

### Expected behavior

I should see a data map export with my new system

### Environment

* Version:
* OS:
* Python Version:
* Docker Version:

### Additional context

_Add any other context about the problem here._

**Comment by mfbrown** [comment]
This was resolved by pulling the latest version and doing a `nox -s clean` then a new dev build. Working as expected now
