### ISSUE TITLE
Make the generate endpoint return more helpful error messages on failure

### ISSUE THREAD

**Issue by allisonking** [ethyca/fides#892]
### Is your feature request related to a specific problem?

Right now if you try to use the generate endpoint to connect to a database that doesn't exist, there will be an internal server error. Therefore, the frontend can only show "An unexpected error occurred". 

### Describe the solution you'd like

We should do our best to catch common error cases (malformed URL, db unreachable) and return that message instead of internal server error-ing.

### Describe alternatives you've considered, if any

_A description of any alternative solutions or features you've considered._

### Additional context

Came up as a result of https://github.com/ethyca/fides/pull/889

Can reproduce with

```
curl -X 'POST' \                                              
  'http://localhost:8080/api/v1/generate/' \
  -H 'accept: application/json' \
  -H 'Content-Type: application/json' \
  -d '{
  "organization_key": "default_organization",
  "generate": {
    "config": {
      "connection_string": "fake_string"
    },
    "target": "db",
    "type": "datasets"
  }
}'
```
which will give an Internal Server Error

**Comment by ssangervasi** [comment]
Encountered something similar while working on [AWS error handling](https://github.com/ethyca/fides/issues/892). Passing malformed credentials will 500 in a strange way.

<details>
<summary>Traceback having passed "lj alsd jlaksj la" as the Access Key ID</summary>

```py
2022-07-12 01:31:42.854 [ERROR] (generate:generate_aws:167): 'alsd' not a valid key=value pair (missing equal-sign) in Authorization header: 'AWS4-HMAC-SHA256 Credential=lj alsd jlaksj la/20220712/af-south-1/redshift/aws4_request, SignedHeaders=content-type;host;x-amz-date, Signature=x'.
2022-07-12 01:31:42.874 [ERROR] (generate:generate_aws:168): Traceback (most recent call last):
  File "/fides/src/fidesctl/connectors/aws.py", line 37, in wrapper_func
    return func(*args, **kwargs)
  File "/fides/src/fidesctl/connectors/aws.py", line 63, in describe_redshift_clusters
    describe_clusters = client.describe_clusters()
  File "/usr/local/lib/python3.8/site-packages/botocore/client.py", line 391, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/usr/local/lib/python3.8/site-packages/botocore/client.py", line 719, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (IncompleteSignature) when calling the DescribeClusters operation: 'alsd' not a valid key=value pair (missing equal-sign) in Authorization header: 'AWS4-HMAC-SHA256 Credential=lj alsd jlaksj la/20220712/af-south-1/redshift/aws4_request, SignedHeaders=content-type;host;x-amz-date, Signature=x'.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/fides/src/fidesapi/routes/generate.py", line 163, in generate_aws
    aws_systems = generate_aws_systems(organization=organization, aws_config=aws_config)
  File "/fides/src/fidesctl/core/system.py", line 100, in generate_aws_systems
    aws_systems = [
  File "/fides/src/fidesctl/core/system.py", line 103, in <listcomp>
    for found_system in generate_function(organization.fides_key, aws_config)
  File "/fides/src/fidesctl/core/system.py", line 29, in generate_redshift_systems
    describe_clusters = aws_connector.describe_redshift_clusters(client=client)
  File "/fides/src/fidesctl/connectors/aws.py", line 44, in wrapper_func
    raise ConnectorFailureException(error.response["Error"]["Message"])
fidesctl.connectors.models.ConnectorFailureException: 'alsd' not a valid key=value pair (missing equal-sign) in Authorization header: 'AWS4-HMAC-SHA256 Credential=lj alsd jlaksj la/20220712/af-south-1/redshift/aws4_request, SignedHeaders=content-type;host;x-amz-date, Signature=x'.
```
</details>

**Comment by ssangervasi** [comment]
Also related: when auth fails, the API will return 403 when reasing [ConnectorAuthFailureException](https://github.com/ethyca/fides/blob/45b473190d431bbc31c84bf6ddd1b4791215af44/src/fidesapi/routes/generate.py#L147). However, the OpenAPI docs don't list this as one of the possible responses. I did some digging and it's a [somewhat common](https://github.com/tiangolo/fastapi/issues/1999) FastAPI complaint that custom exceptions like this require extra documenting.

**Comment by ssangervasi** [comment]
The UI for AWS scan errors also demands a pretty detailed log of the generate attempt:
https://www.figma.com/file/NeFvOOb1RT2fcdqZT0vBF2/Fidesctl-Management-UI?node-id=59%3A2035

<details>
<summary>I assume this log is copied a CLI example?</summary>

```
2022-04-14 16:57:23.855 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432

2022-04-14 16:57:23.855 UTC [1] LOG:  listening on IPv6 address "::", port 5432

2022-04-14 16:57:23.856 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"

2022-04-14 16:57:23.870 UTC [27] LOG:  database system was shut down at 2022-04-14 16:57:04 UTC

2022-04-14 16:57:23.875 UTC [1] LOG:  database system is ready to accept connections
```

</details>

**Comment by SteveDMurphy** [comment]
I think some of this stems from the need we have to separate CLI and Core functionality. We have been doing this more and more as we go froward but it sounds like some better separation (i.e. validating the engine) would allow for better introspection and error handling here
